--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11 (Homebrew)
-- Dumped by pg_dump version 17.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: nombre_dia(date); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.nombre_dia(date) RETURNS text
    LANGUAGE sql
    AS $_$
select case extract(dow from $1)
            when 1 then 'lunes'
            when 2 then 'martes'
            when 3 then 'miercoles'
            when 4 then 'jueves'
            when 5 then 'viernes'
            when 6 then 'sabado'
            else 'domingo'
       end;
$_$;


--
-- Name: nombre_mes(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.nombre_mes() RETURNS text
    LANGUAGE plpgsql
    AS $$
declare
mes text:='';
begin
mes:=( SELECT case (to_char(now(), 'TMMonth'))
            when 'January' then 'Enero'
			when 'Enero' then 'Enero'
            when 'February' then 'Febrero'
			when 'Febrero' then 'Febrero'
            when 'March' then 'Marzo'
			when 'Marzo' then 'Marzo'
            when 'April' then 'Abril'
			when 'Abril' then 'Abril'
            when 'May' then 'Mayo'
			when 'Mayo' then 'Mayo'
            when 'June' then 'Junio'
			when 'Junio' then 'Junio'
			when 'July' then 'Julio'
			when 'Julio' then 'Julio'
			when 'August' then 'Agosto'
			when 'Agosto' then 'Agosto'
			when 'September' then 'Septiembre'
			when 'Septiembre' then 'Septiembre'
			when 'Octuber' then 'Octubre'
			when 'Octubre' then 'Octubre'
			when 'November' then 'Noviembre'
			when 'Noviembre' then 'Noviembre'
			else 'Diciembre' 
end);
	return mes;
end ;
$$;


--
-- Name: periodos_mes(); Type: PROCEDURE; Schema: public; Owner: -
--

CREATE PROCEDURE public.periodos_mes()
    LANGUAGE plpgsql
    AS $$
declare 
	mes1 int;mes2 int;dia text;daydate date;start_dates date;end_dates date;weeks int=0;year1 int;monthtxts text;
	firstdate date =(select date_trunc('month',current_date)::date);
begin
	dia :=(select nombre_dia(firstdate));
	daydate :=firstdate;
	--while-----
	while (dia!='lunes')
		loop
			daydate :=daydate + INTERVAL '1 days';
			dia :=(select nombre_dia(daydate));
			mes1:=(select extract(month from  daydate));
			mes2:=(select extract(month from  daydate));
			year1:=(select extract(year from  daydate));
		end loop;
	--fin while--
	-------------------------------------------
	---if--
	if not exists(select * from "period" where "months"=mes1 and "years"=year1)then
	--while------
		start_dates=daydate;
		monthtxts:=(select nombre_mes());
		while(mes2=mes1)
			loop
				end_dates=start_dates + INTERVAL '6 DAYS';
				weeks=weeks+1;
				insert into period(start_date,end_date,months,theme1,theme2,week,years,monthtxt) 
				values(start_dates,end_dates,mes1,'sin definir','sin definir',weeks,year1,monthtxts);
				start_dates=start_dates + INTERVAL '7 DAYS';
				mes2:=(select extract(month from  start_dates));
			end loop;
		--fin while--
	end if;
	--fin if--
end;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    id_attendance integer NOT NULL,
    offering character varying(255) NOT NULL,
    id_cel integer NOT NULL,
    id_period integer NOT NULL
);


--
-- Name: attendance_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_detail (
    id_attendance_detail integer NOT NULL,
    attended boolean NOT NULL,
    id_member_cell integer NOT NULL,
    id_atten integer NOT NULL
);


--
-- Name: attendance_detail_id_attendance_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_detail ALTER COLUMN id_attendance_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_detail_id_attendance_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_id_attendance_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id_attendance ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_attendance_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cell; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cell (
    id_cell integer NOT NULL,
    address character varying(255) NOT NULL,
    cellular character varying(12) NOT NULL,
    day character varying(255) NOT NULL,
    grid character varying(1) NOT NULL,
    hour character varying(255) NOT NULL,
    level character varying(255) NOT NULL,
    observations character varying(255),
    open_date timestamp(6) without time zone NOT NULL,
    phone character varying(12) NOT NULL,
    photo_url character varying(255) NOT NULL,
    reference character varying(255) NOT NULL,
    state boolean NOT NULL,
    type character varying(1) NOT NULL
);


--
-- Name: cell_id_cell_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cell ALTER COLUMN id_cell ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cell_id_cell_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: change_cell; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.change_cell (
    id_change_cell integer NOT NULL,
    change_date timestamp(6) without time zone NOT NULL,
    id_member_cell_new integer NOT NULL,
    id_member_cell_old integer NOT NULL
);


--
-- Name: change_cell_id_change_cell_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.change_cell ALTER COLUMN id_change_cell ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.change_cell_id_change_cell_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guest (
    id_guest integer NOT NULL,
    id_cell integer NOT NULL,
    id_period integer NOT NULL,
    id_person integer NOT NULL
);


--
-- Name: guest_id_guest_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.guest ALTER COLUMN id_guest ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guest_id_guest_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: history_person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.history_person (
    id_history_person integer NOT NULL,
    id_table integer,
    name_table character varying(255),
    register_date timestamp(6) without time zone NOT NULL
);


--
-- Name: history_person_id_history_person_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.history_person ALTER COLUMN id_history_person ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.history_person_id_history_person_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_cell; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_cell (
    id_member_cell integer NOT NULL,
    state boolean NOT NULL,
    type_member_cell character varying(255),
    id_cell integer NOT NULL,
    id_person integer NOT NULL
);


--
-- Name: member_cell_id_member_cell_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_cell ALTER COLUMN id_member_cell ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_cell_id_member_cell_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu (
    id_menu integer NOT NULL,
    icon character varying(20) NOT NULL,
    name character varying(20) NOT NULL,
    state boolean NOT NULL,
    url character varying(50) NOT NULL
);


--
-- Name: menu_id_menu_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu ALTER COLUMN id_menu ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_menu_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_role (
    id_menu integer NOT NULL,
    id_role integer NOT NULL
);


--
-- Name: period; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.period (
    id_period integer NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    months integer NOT NULL,
    monthtxt character varying(255),
    start_date timestamp(6) without time zone NOT NULL,
    theme1 character varying(255),
    theme2 character varying(255),
    week integer NOT NULL,
    years integer NOT NULL
);


--
-- Name: period_id_period_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.period ALTER COLUMN id_period ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.period_id_period_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    id_person integer NOT NULL,
    address character varying(255) NOT NULL,
    birth_date timestamp(6) without time zone NOT NULL,
    cellular character varying(12) NOT NULL,
    civil_status character varying(1) NOT NULL,
    email character varying(255) NOT NULL,
    genre character varying(1) NOT NULL,
    maternal_surname character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    number_doc character varying(10) NOT NULL,
    paternal_surname character varying(255) NOT NULL,
    phone character varying(12),
    photo_url character varying(255),
    reference character varying(255) NOT NULL,
    type_doc character varying(1) NOT NULL
);


--
-- Name: person_id_person_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.person ALTER COLUMN id_person ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_person_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    id_role integer NOT NULL,
    name character varying(70) NOT NULL,
    state boolean NOT NULL
);


--
-- Name: role_id_role_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spiritual_growth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spiritual_growth (
    id_spiritual_growth integer NOT NULL,
    description character varying(255) NOT NULL,
    state boolean NOT NULL
);


--
-- Name: spiritual_growth_id_spiritual_growth_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.spiritual_growth ALTER COLUMN id_spiritual_growth ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spiritual_growth_id_spiritual_growth_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spiritual_growth_person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spiritual_growth_person (
    id_spiritual_growth_person integer NOT NULL,
    date timestamp(6) without time zone,
    periodo character varying(255),
    id_person integer NOT NULL,
    id_spiritual_growth integer NOT NULL
);


--
-- Name: user_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_data (
    id_user integer NOT NULL,
    password character varying(255) NOT NULL,
    state boolean NOT NULL,
    username character varying(60) NOT NULL,
    id_person integer NOT NULL
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_role (
    id_user integer NOT NULL,
    id_role integer NOT NULL
);


--
-- Name: attendance_detail attendance_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_detail
    ADD CONSTRAINT attendance_detail_pkey PRIMARY KEY (id_attendance_detail);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id_attendance);


--
-- Name: cell cell_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cell
    ADD CONSTRAINT cell_pkey PRIMARY KEY (id_cell);


--
-- Name: change_cell change_cell_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.change_cell
    ADD CONSTRAINT change_cell_pkey PRIMARY KEY (id_change_cell);


--
-- Name: guest guest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT guest_pkey PRIMARY KEY (id_guest);


--
-- Name: history_person history_person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.history_person
    ADD CONSTRAINT history_person_pkey PRIMARY KEY (id_history_person);


--
-- Name: member_cell member_cell_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_cell
    ADD CONSTRAINT member_cell_pkey PRIMARY KEY (id_member_cell);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id_menu);


--
-- Name: period period_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.period
    ADD CONSTRAINT period_pkey PRIMARY KEY (id_period);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id_person);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id_role);


--
-- Name: spiritual_growth_person spiritual_growth_person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spiritual_growth_person
    ADD CONSTRAINT spiritual_growth_person_pkey PRIMARY KEY (id_spiritual_growth_person);


--
-- Name: spiritual_growth spiritual_growth_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spiritual_growth
    ADD CONSTRAINT spiritual_growth_pkey PRIMARY KEY (id_spiritual_growth);


--
-- Name: person uk52uphcj73s7bgfj1wklt97ywh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT uk52uphcj73s7bgfj1wklt97ywh UNIQUE (number_doc);


--
-- Name: user_data uknlc4atex50p892vsfhwccm336; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_data
    ADD CONSTRAINT uknlc4atex50p892vsfhwccm336 UNIQUE (username);


--
-- Name: user_data user_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_data
    ADD CONSTRAINT user_data_pkey PRIMARY KEY (id_user);


--
-- Name: user_role fk2aam9nt2tv8vcfymi3jo9c314; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk2aam9nt2tv8vcfymi3jo9c314 FOREIGN KEY (id_role) REFERENCES public.role(id_role);


--
-- Name: menu_role fk2ymscnycm83uqu1ddpkgdryg1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_role
    ADD CONSTRAINT fk2ymscnycm83uqu1ddpkgdryg1 FOREIGN KEY (id_menu) REFERENCES public.menu(id_menu);


--
-- Name: user_role fk9qphm07p6th93qb8p9fnykvwo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk9qphm07p6th93qb8p9fnykvwo FOREIGN KEY (id_user) REFERENCES public.user_data(id_user);


--
-- Name: attendance fk_attendance_cell; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk_attendance_cell FOREIGN KEY (id_cel) REFERENCES public.cell(id_cell);


--
-- Name: attendance fk_attendance_period; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk_attendance_period FOREIGN KEY (id_period) REFERENCES public.period(id_period);


--
-- Name: attendance_detail fk_attendetail_atten; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_detail
    ADD CONSTRAINT fk_attendetail_atten FOREIGN KEY (id_atten) REFERENCES public.attendance(id_attendance);


--
-- Name: attendance_detail fk_attendetail_membercell; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_detail
    ADD CONSTRAINT fk_attendetail_membercell FOREIGN KEY (id_member_cell) REFERENCES public.member_cell(id_member_cell);


--
-- Name: change_cell fk_changecellnew_cellmember; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.change_cell
    ADD CONSTRAINT fk_changecellnew_cellmember FOREIGN KEY (id_member_cell_new) REFERENCES public.member_cell(id_member_cell);


--
-- Name: change_cell fk_changecellold_cellmember; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.change_cell
    ADD CONSTRAINT fk_changecellold_cellmember FOREIGN KEY (id_member_cell_old) REFERENCES public.member_cell(id_member_cell);


--
-- Name: guest fk_guest_cell; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT fk_guest_cell FOREIGN KEY (id_cell) REFERENCES public.cell(id_cell);


--
-- Name: guest fk_guest_period; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT fk_guest_period FOREIGN KEY (id_period) REFERENCES public.period(id_period);


--
-- Name: guest fk_guest_person; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guest
    ADD CONSTRAINT fk_guest_person FOREIGN KEY (id_person) REFERENCES public.person(id_person);


--
-- Name: member_cell fk_membercell_cell; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_cell
    ADD CONSTRAINT fk_membercell_cell FOREIGN KEY (id_cell) REFERENCES public.cell(id_cell);


--
-- Name: member_cell fk_membercell_person; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_cell
    ADD CONSTRAINT fk_membercell_person FOREIGN KEY (id_person) REFERENCES public.person(id_person);


--
-- Name: spiritual_growth_person fk_spiritualgrowthperson_person; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spiritual_growth_person
    ADD CONSTRAINT fk_spiritualgrowthperson_person FOREIGN KEY (id_person) REFERENCES public.person(id_person);


--
-- Name: spiritual_growth_person fk_spiritualgrowthperson_spiritualgrowth; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spiritual_growth_person
    ADD CONSTRAINT fk_spiritualgrowthperson_spiritualgrowth FOREIGN KEY (id_spiritual_growth) REFERENCES public.spiritual_growth(id_spiritual_growth);


--
-- Name: user_data fk_user_person; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_data
    ADD CONSTRAINT fk_user_person FOREIGN KEY (id_person) REFERENCES public.person(id_person);


--
-- Name: menu_role fkbhl7xy7xjv54q9vedxuxk2kn0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_role
    ADD CONSTRAINT fkbhl7xy7xjv54q9vedxuxk2kn0 FOREIGN KEY (id_role) REFERENCES public.role(id_role);


--
-- PostgreSQL database dump complete
--



